### ISSUE TITLE
🐛 弹幕解析似乎有点问题

### ISSUE THREAD

**Issue by MySlientWind** [yutto-dev/yutto#110]
### 问题简述

`yutto https://www.bilibili.com/video/BV14A411c78B` 报错
```
Traceback (most recent call last):
  File "C:\Users\{username}\anaconda3\envs\py395\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\{username}\anaconda3\envs\py395\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\{username}\anaconda3\envs\py395\Scripts\yutto.exe\__main__.py", line 7, in <module>
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\__main__.py", line 52, in main
    run(args_list)
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\utils\funcutils\as_sync.py", line 33, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "C:\Users\{username}\anaconda3\envs\py395\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\{username}\anaconda3\envs\py395\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\__main__.py", line 250, in run
    episode_data = await episode_data_coro
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\extractor\common.py", line 95, in extract_ugc_video_data
    danmaku = await get_danmaku(session, cid, args.danmaku_format) if args.require_danmaku else EmptyDanmakuData
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\api\danmaku.py", line 39, in get_danmaku
    danmaku_data["data"].append(await get_xml_danmaku(session, cid))
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\api\danmaku.py", line 13, in get_xml_danmaku
    assert results is not None
AssertionError
```
不下载弹幕或采用 protobuf 格式就可以正常下载视频
`yutto https://www.bilibili.com/video/BV14A411c78B --no-danmaku` 没有问题
`yutto https://www.bilibili.com/video/BV14A411c78B --danmaku-format protobuf` 没有问题

debug 信息为
```
DEBUG  Windows 平台，单独设置 EventLoopPolicy
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 DEBUG  Get redircted url: https://www.bilibili.com/video/BV14A411c78B -> https://www.bilibili.com/video/BV14A411c78B/
 DEBUG  Fetch json: http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV14A411c78B
 DEBUG  Fetch json: https://api.bilibili.com/x/player/pagelist?aid=&bvid=BV14A411c78B&jsonp=jsonp
 投稿视频  我的世界 爆炸弓 数据包乱做视频
 DEBUG  Fetch json: https://api.bilibili.com/x/player/playurl?avid=&bvid=BV14A411c78B&cid=396628236&qn=127&type=&otype=json&fnver=0&fnval=4048&fourk=1
 DEBUG  Fetch text: https://api.bilibili.com/x/player.so?aid=&bvid=BV14A411c78B&id=cid:396628236
 DEBUG  Fetch text: http://comment.bilibili.com/396628236.xml
Traceback (most recent call last):
  File "C:\Users\{username}\anaconda3\envs\py395\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\{username}\anaconda3\envs\py395\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\{username}\anaconda3\envs\py395\Scripts\yutto.exe\__main__.py", line 7, in <module>
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\__main__.py", line 52, in main
    run(args_list)
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\utils\funcutils\as_sync.py", line 33, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "C:\Users\{username}\anaconda3\envs\py395\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\{username}\anaconda3\envs\py395\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\__main__.py", line 250, in run
    episode_data = await episode_data_coro
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\extractor\common.py", line 95, in extract_ugc_video_data
    danmaku = await get_danmaku(session, cid, args.danmaku_format) if args.require_danmaku else EmptyDanmakuData
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\api\danmaku.py", line 39, in get_danmaku
    danmaku_data["data"].append(await get_xml_danmaku(session, cid))
  File "C:\Users\{username}\anaconda3\envs\py395\lib\site-packages\yutto\api\danmaku.py", line 13, in get_xml_danmaku
    assert results is not None
AssertionError
```
看起来是因为 http://comment.bilibili.com/396628236.xml 这个链接下不到弹幕了

### 复现方式

`yutto https://www.bilibili.com/video/BV14A411c78B` 或其他任意视频

### 环境信息

-  OS: win11 22000.1455
-  Python: Python 3.9.15
-  yutto: yutto 2.0.0-beta.20
-  FFmpeg: ffmpeg version N-81989-g7845c13

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
看报错应该确实是下载不到 xml 弹幕，但我这里不能复现这个问题

> 看起来是因为 http://comment.bilibili.com/396628236.xml 这个链接下不到弹幕了

我这里也是能获取的

也许是因为下载太多了 IP 触发了某些限制？

**Comment by MySlientWind** [comment]
好像确实是个临时问题，现在又好了，那我 close 了。
