### ISSUE TITLE
🐛 RuntimeWarning: coroutine 'extract_ugc_video_data' was never awaited

### ISSUE THREAD

**Issue by x1ntt** [yutto-dev/yutto#116]
### 问题简述

使用podman运行时出现的问题，完整错误如下

```Shell
 INFO  成功使用 uvloop 加速协程
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 UP 主投稿视频  吃了个迟x
 [1/105]  在逃公主的高跟鞋！
 INFO  开始处理视频 在逃公主的高跟鞋！
 INFO  共包含以下 6 个视频流：
 INFO  * 0 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO    1 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO    2 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO    3 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO    4 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO    5 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
Traceback (most recent call last):
  File "/usr/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 52, in main
    run(args_list)
  File "/usr/lib/python3.10/site-packages/yutto/utils/funcutils/as_sync.py", line 33, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 258, in run
    await start_downloader(
  File "/usr/lib/python3.10/site-packages/yutto/processor/downloader.py", line 249, in start_downloader
    write_danmaku(
  File "/usr/lib/python3.10/site-packages/yutto/utils/danmaku.py", line 78, in write_danmaku
    write_ass_danmaku(xml_danmaku, "xml", file_path, height, width)
  File "/usr/lib/python3.10/site-packages/yutto/utils/danmaku.py", line 42, in write_ass_danmaku
    with open(
PermissionError: [Errno 13] Permission denied: '/app/吃了个迟x/在逃公主的高跟鞋！_2023-03-04/在逃公主的高跟鞋！.ass'
sys:1: RuntimeWarning: coroutine 'extract_ugc_video_data' was never awaited
```

### 复现方式

参数如下
```Shell
DOCKER_ARGS="--rm -v"
ARGS="-b -tp {username}/{name}_{pubdate}/{name}"

function download_v(){
        podman run $DOCKER_ARGS $(pwd):/app siguremo/yutto https://space.bilibili.com/$1/video $ARGS
}
```

必然出现问题

### 环境信息

+ 系统
    `RockyLinux9.1`
+ uname -a
    `Linux nuc11 5.14.0-162.18.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 1 22:02:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by x1ntt** [comment]
还有这个
```shell
[st@localhost export]$ sudo docker run --rm -it -v .:/app siguremo/yutto https://www.bilibili.com/video/BV1vZ4y1M7mQ
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Resolving "siguremo/yutto" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/siguremo/yutto:latest...
Getting image source signatures
Copying blob a7752b4922db done
Copying blob 14c8f4b5d94a done
Copying blob 8921db27df28 done
Copying config 2fbc3b0e3d done
Writing manifest to image destination
Storing signatures
 INFO  成功使用 uvloop 加速协程
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 投稿视频  用 bilili 下载 B 站视频
 INFO  开始处理视频 用 bilili 下载 B 站视频
 INFO  共包含以下 2 个视频流：
 INFO  * 0 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO    1 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
Traceback (most recent call last):
  File "/usr/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 52, in main
    run(args_list)
  File "/usr/lib/python3.10/site-packages/yutto/utils/funcutils/as_sync.py", line 33, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 258, in run
    await start_downloader(
  File "/usr/lib/python3.10/site-packages/yutto/processor/downloader.py", line 249, in start_downloader
    write_danmaku(
  File "/usr/lib/python3.10/site-packages/yutto/utils/danmaku.py", line 78, in write_danmaku
    write_ass_danmaku(xml_danmaku, "xml", file_path, height, width)
  File "/usr/lib/python3.10/site-packages/yutto/utils/danmaku.py", line 42, in write_ass_danmaku
    with open(
PermissionError: [Errno 13] Permission denied: '/app/用 bilili 下载 B 站视频.ass'
```

**Comment by SigureMo** [comment]
emmm，不太清楚，我这里用 docker 无法复现，看起来像是 `/app` 绑定的当前路径 `$(pwd)` 没有写入权限……

**Comment by x1ntt** [comment]
> emmm，不太清楚，我这里用 docker 无法复现，看起来像是 `/app` 绑定的当前路径 `$(pwd)` 没有写入权限……

找到原因了，这个问题是因为`RockyLinux`上面的`SELinux`导致的，它对权限的管理真的是离谱过头了（以至于我的`samba`都访问不到

假设原有命令如下
`podman run --rm -it -v .:/app siguremo/yutto https://www.bilibili.com/video/BV1vZ4y1M7mQ`

这个问题有两个解决方案，
+ 对`-v`参数增加`z`
   也即是`podman run --rm -it -v .:/app:z siguremo/yutto https://www.bilibili.com/video/BV1vZ4y1M7mQ`
   其本质见这里[https://projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/](https://projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)。加过一次`z`之后，下次就不用了
+ 添加参数 `--privileged`
    也即是`podman run --privileged --rm -it -v .:/app siguremo/yutto https://www.bilibili.com/video/BV1vZ4y1M7mQ`
    `--privileged` 选项禁用将容器与主机隔离的安全功能。所以一般感觉上面的方案会更合适
以上两个方法来自于 [https://www.reddit.com/r/jellyfin/comments/b2bs1x/docker_permission_issues/](https://www.reddit.com/r/jellyfin/comments/b2bs1x/docker_permission_issues/)

当然还有更彻底的，就是关掉`SELinux` (万恶啊...

**Comment by SigureMo** [comment]
> 可以考虑将这个补充到`readme`中

这个是不会考虑的，因为本问题与 yutto 没有任何关系，只是环境权限管理的问题，这样的问题用户应该自行按照自己的环境配置来搜索对应的解决方案

**Comment by x1ntt** [comment]
> > 可以考虑将这个补充到`readme`中
> 
> 这个是不会考虑的，因为本问题与 yutto 没有任何关系，只是环境权限管理的问题，这样的问题用户应该自行按照自己的环境配置来搜索对应的解决方案

原来如此，没问题了
