### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by temco** [yutto-dev/yutto#170]
### 问题简述

 DEBUG  Fetch json: https://api.bilibili.com/x/web-interface/nav
 大会员  成功以大会员身份登录～
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 DEBUG  Get redircted url: https://www.bilibili.com/video/BV18N411C7Ns/?spm_id_from=333.999.0.0
 DEBUG  Fetch json: http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
 WARN  抓取失败（InvalidURL），正在重试，剩余 2 次
 DEBUG  Fetch json: http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
 WARN  抓取失败（InvalidURL），正在重试，剩余 1 次
 DEBUG  Fetch json: http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
 WARN  抓取失败（InvalidURL），正在重试，剩余 0 次
Traceback (most recent call last):
  File "/usr/local/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/__main__.py", line 57, in main
    run(args_list)
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/utils/funcutils/as_sync.py", line 34, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/__main__.py", line 251, in run
    download_list = await extractor(session, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/extractor/_abc.py", line 36, in __call__
    return [await self.extract(session, args)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/extractor/ugc_video.py", line 68, in extract
    ugc_video_list = await get_ugc_video_list(session, self.avid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/api/ugc_video.py", line 127, in get_ugc_video_list
    video_info = await get_ugc_video_info(session, avid)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/api/ugc_video.py", line 82, in get_ugc_video_info
    res_json = await Fetcher.fetch_json(session, info_api.format(**avid.to_dict()))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yutto/2.0.0b28/libexec/lib/python3.11/site-packages/yutto/utils/fetcher.py", line 48, in connect_n_times
    raise MaxRetryError("超出最大重试次数！")
yutto.exceptions.MaxRetryError: 超出最大重试次数！

### 复现方式

yutto -c "f1f8180c...AQAAOgA" https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0 --debug

### 环境信息

-  OS: macOS 12.6.7
-  Python: Python 3.9.13
-  yutto: yutto 2.0.0-beta.28
-  FFmpeg: ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers built with Apple clang version 14.0.0 (clang-1400.0.29.202)

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
无法复现，重试几次呢？

**Comment by temco** [comment]
> 无法复现，重试几次呢？

不行的，我有三台硬件一样的macbook(软件上差异也不大)，就是这一台是无法运行成功的

**Comment by lc4t** [comment]
`yutto -c "f1f8180c...AQAAOgA" [https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0](https://www.bilibili.com/video/BV18N411C7Ns/%5C?spm_id_from%5C=333.999.0.0) --debug`
这里，猜测是你shell环境有自动转义`?=`这类字符，粘贴后把`\?`,`\=`中的反斜杠删掉再试试能不能复现~  @temco

**Comment by temco** [comment]
> `yutto -c "f1f8180c...AQAAOgA" [https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0](https://www.bilibili.com/video/BV18N411C7Ns/%5C?spm_id_from%5C=333.999.0.0) --debug` 这里，猜测是你shell环境有自动转义`?=`这类字符，粘贴后把`\?`,`\=`中的**反斜杠**删掉再试试能不能复现~ @temco

并不是这个缘故，我其实一般都会把后面的指令部分都删掉、贴纯地址进去的，也是不行的
运行的时候，可以发现不仅大会员登录是正常的，其实根据我给的地址转译的json地址也是正确的，但就是fetch不下来，不知道我这台机器的网络设置有什么奇怪之处，也许是因为有两层VPN？但我切成手机连出去好像也没成功

**Comment by lc4t** [comment]
> > `yutto -c "f1f8180c...AQAAOgA" [https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0](https://www.bilibili.com/video/BV18N411C7Ns/%5C?spm_id_from%5C=333.999.0.0) --debug` 这里，猜测是你shell环境有自动转义`?=`这类字符，粘贴后把`\?`,`\=`中的**反斜杠**删掉再试试能不能复现~ @temco
> 
> 并不是这个缘故，我其实一般都会把后面的指令部分都删掉、贴纯地址进去的，也是不行的 运行的时候，可以发现不仅大会员登录是正常的，其实根据我给的地址转译的json地址也是正确的，但就是fetch不下来，不知道我这台机器的网络设置有什么奇怪之处，也许是因为有两层VPN？但我切成手机连出去好像也没成功

失败的URL是`http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns`，如果不使用yutto也失败的话那就需要你自己看看是不是配置问题咯。

可以试着直接浏览器访问下上面的链接，如果可以成功的话，copy as curl(去掉cookie)在运行yutto的命令行中试一下

**Comment by temco** [comment]
> > > `yutto -c "f1f8180c...AQAAOgA" [https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0](https://www.bilibili.com/video/BV18N411C7Ns/%5C?spm_id_from%5C=333.999.0.0) --debug` 这里，猜测是你shell环境有自动转义`?=`这类字符，粘贴后把`\?`,`\=`中的**反斜杠**删掉再试试能不能复现~ @temco
> > 
> > 
> > 并不是这个缘故，我其实一般都会把后面的指令部分都删掉、贴纯地址进去的，也是不行的 运行的时候，可以发现不仅大会员登录是正常的，其实根据我给的地址转译的json地址也是正确的，但就是fetch不下来，不知道我这台机器的网络设置有什么奇怪之处，也许是因为有两层VPN？但我切成手机连出去好像也没成功
> 
> 失败的URL是`http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns`，如果不使用yutto也失败的话那就需要你自己看看是不是配置问题咯。
> 
> 可以试着直接浏览器访问下上面的链接，如果可以成功的话，copy as curl(去掉cookie)在运行yutto的命令行中试一下

`http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns`这个地址在浏览器中是可以访问的，因为会自动切换成https，直接去curl是取不到的，改成https再去curl就取得到了

**Comment by lc4t** [comment]
> > > > `yutto -c "f1f8180c...AQAAOgA" [https://www.bilibili.com/video/BV18N411C7Ns/\?spm_id_from\=333.999.0.0](https://www.bilibili.com/video/BV18N411C7Ns/%5C?spm_id_from%5C=333.999.0.0) --debug` 这里，猜测是你shell环境有自动转义`?=`这类字符，粘贴后把`\?`,`\=`中的**反斜杠**删掉再试试能不能复现~ @temco
> > > 
> > > 
> > > 并不是这个缘故，我其实一般都会把后面的指令部分都删掉、贴纯地址进去的，也是不行的 运行的时候，可以发现不仅大会员登录是正常的，其实根据我给的地址转译的json地址也是正确的，但就是fetch不下来，不知道我这台机器的网络设置有什么奇怪之处，也许是因为有两层VPN？但我切成手机连出去好像也没成功
> > 
> > 
> > 失败的URL是`http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns`，如果不使用yutto也失败的话那就需要你自己看看是不是配置问题咯。
> > 可以试着直接浏览器访问下上面的链接，如果可以成功的话，copy as curl(去掉cookie)在运行yutto的命令行中试一下
> 
> `http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns`这个地址在浏览器中是可以访问的，因为会自动切换成https，直接去curl是取不到的，改成https再去curl就取得到了

按理说yutto会自动跳转的，可以给下有问题的机器上的`curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'`输出吗？

**Comment by temco** [comment]
> curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'

```
curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'
* Uses proxy env variable ALL_PROXY == '127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
* Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> GET http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns HTTP/1.1
> Host: api.bilibili.com
> User-Agent: curl/7.84.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Content-Length: 241
< Cache-Control: no-cache
< Connection: keep-alive
< Content-Type: text/html
< Date: Thu, 07 Sep 2023 02:51:17 GMT
< Expires: Thu, 07 Sep 2023 02:51:16 GMT
< Keep-Alive: timeout=4
< Location: https://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
< Proxy-Connection: keep-alive
< Server: Tengine
< X-Cache-Webcdn: BYPASS from blzone03
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>307 Temporary Redirect</title></head>
<body>
<center><h1>307 Temporary Redirect</h1></center>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

```
traceroute  api.bilibili.com
traceroute: Warning: api.bilibili.com has multiple addresses; using 175.4.62.127
traceroute to a.w.bilicdn1.com (175.4.62.127), 64 hops max, 52 byte packets
 1  * * *
 2  192.168.10.1 (192.168.10.1)  3.243 ms  2.644 ms  3.129 ms
 3  183.129.155.33 (183.129.155.33)  6.603 ms  4.509 ms  5.121 ms
 4  61.164.12.30 (61.164.12.30)  4.155 ms * *
 5  122.224.191.33 (122.224.191.33)  8.802 ms
    115.233.18.41 (115.233.18.41)  3.966 ms
    60.191.25.129 (60.191.25.129)  6.983 ms
 6  202.97.77.14 (202.97.77.14)  23.924 ms
    202.97.77.10 (202.97.77.10)  20.544 ms
    202.97.27.174 (202.97.27.174)  19.943 ms
 7  61.137.11.202 (61.137.11.202)  22.976 ms
    61.137.6.242 (61.137.6.242)  22.252 ms
    61.137.14.46 (61.137.14.46)  23.235 ms
 8  * * *
 9  * * *
10  * * *
11  175.4.62.127 (175.4.62.127)  22.465 ms  22.831 ms  22.682 ms
```

**Comment by lc4t** [comment]
> > curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'
> 
> ```
> curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'
> * Uses proxy env variable ALL_PROXY == '127.0.0.1:7890'
> *   Trying 127.0.0.1:7890...
> * Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> > GET http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns HTTP/1.1
> > Host: api.bilibili.com
> > User-Agent: curl/7.84.0
> > Accept: */*
> > Proxy-Connection: Keep-Alive
> > 
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 307 Temporary Redirect
> < Content-Length: 241
> < Cache-Control: no-cache
> < Connection: keep-alive
> < Content-Type: text/html
> < Date: Thu, 07 Sep 2023 02:51:17 GMT
> < Expires: Thu, 07 Sep 2023 02:51:16 GMT
> < Keep-Alive: timeout=4
> < Location: https://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
> < Proxy-Connection: keep-alive
> < Server: Tengine
> < X-Cache-Webcdn: BYPASS from blzone03
> < 
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html>
> <head><title>307 Temporary Redirect</title></head>
> <body>
> <center><h1>307 Temporary Redirect</h1></center>
> <hr/>Powered by Tengine<hr><center>tengine</center>
> </body>
> </html>
> * Connection #0 to host 127.0.0.1 left intact
> ```
> 
> ```
> traceroute  api.bilibili.com
> traceroute: Warning: api.bilibili.com has multiple addresses; using 175.4.62.127
> traceroute to a.w.bilicdn1.com (175.4.62.127), 64 hops max, 52 byte packets
>  1  * * *
>  2  192.168.10.1 (192.168.10.1)  3.243 ms  2.644 ms  3.129 ms
>  3  183.129.155.33 (183.129.155.33)  6.603 ms  4.509 ms  5.121 ms
>  4  61.164.12.30 (61.164.12.30)  4.155 ms * *
>  5  122.224.191.33 (122.224.191.33)  8.802 ms
>     115.233.18.41 (115.233.18.41)  3.966 ms
>     60.191.25.129 (60.191.25.129)  6.983 ms
>  6  202.97.77.14 (202.97.77.14)  23.924 ms
>     202.97.77.10 (202.97.77.10)  20.544 ms
>     202.97.27.174 (202.97.27.174)  19.943 ms
>  7  61.137.11.202 (61.137.11.202)  22.976 ms
>     61.137.6.242 (61.137.6.242)  22.252 ms
>     61.137.14.46 (61.137.14.46)  23.235 ms
>  8  * * *
>  9  * * *
> 10  * * *
> 11  175.4.62.127 (175.4.62.127)  22.465 ms  22.831 ms  22.682 ms
> ```

从`curl`没发现什么问题...看起来是你的环境触发了什么bug...

方案1：看看能不能通过docker运行yutto，是否会出错？
方案2：参考下README最下面的贡献方式，在poetry这个环境下运行是否会出错，如果出错，改下代码可以在报错的地方把InvalidURL的上下文输出一下

**Comment by temco** [comment]
> > > curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'
> > 
> > 
> > ```
> > curl -vv 'http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns'
> > * Uses proxy env variable ALL_PROXY == '127.0.0.1:7890'
> > *   Trying 127.0.0.1:7890...
> > * Connected to 127.0.0.1 (127.0.0.1) port 7890 (#0)
> > > GET http://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns HTTP/1.1
> > > Host: api.bilibili.com
> > > User-Agent: curl/7.84.0
> > > Accept: */*
> > > Proxy-Connection: Keep-Alive
> > > 
> > * Mark bundle as not supporting multiuse
> > < HTTP/1.1 307 Temporary Redirect
> > < Content-Length: 241
> > < Cache-Control: no-cache
> > < Connection: keep-alive
> > < Content-Type: text/html
> > < Date: Thu, 07 Sep 2023 02:51:17 GMT
> > < Expires: Thu, 07 Sep 2023 02:51:16 GMT
> > < Keep-Alive: timeout=4
> > < Location: https://api.bilibili.com/x/web-interface/view?aid=&bvid=BV18N411C7Ns
> > < Proxy-Connection: keep-alive
> > < Server: Tengine
> > < X-Cache-Webcdn: BYPASS from blzone03
> > < 
> > <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> > <html>
> > <head><title>307 Temporary Redirect</title></head>
> > <body>
> > <center><h1>307 Temporary Redirect</h1></center>
> > <hr/>Powered by Tengine<hr><center>tengine</center>
> > </body>
> > </html>
> > * Connection #0 to host 127.0.0.1 left intact
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > traceroute  api.bilibili.com
> > traceroute: Warning: api.bilibili.com has multiple addresses; using 175.4.62.127
> > traceroute to a.w.bilicdn1.com (175.4.62.127), 64 hops max, 52 byte packets
> >  1  * * *
> >  2  192.168.10.1 (192.168.10.1)  3.243 ms  2.644 ms  3.129 ms
> >  3  183.129.155.33 (183.129.155.33)  6.603 ms  4.509 ms  5.121 ms
> >  4  61.164.12.30 (61.164.12.30)  4.155 ms * *
> >  5  122.224.191.33 (122.224.191.33)  8.802 ms
> >     115.233.18.41 (115.233.18.41)  3.966 ms
> >     60.191.25.129 (60.191.25.129)  6.983 ms
> >  6  202.97.77.14 (202.97.77.14)  23.924 ms
> >     202.97.77.10 (202.97.77.10)  20.544 ms
> >     202.97.27.174 (202.97.27.174)  19.943 ms
> >  7  61.137.11.202 (61.137.11.202)  22.976 ms
> >     61.137.6.242 (61.137.6.242)  22.252 ms
> >     61.137.14.46 (61.137.14.46)  23.235 ms
> >  8  * * *
> >  9  * * *
> > 10  * * *
> > 11  175.4.62.127 (175.4.62.127)  22.465 ms  22.831 ms  22.682 ms
> > ```
> 
> 从`curl`没发现什么问题...看起来是你的环境触发了什么bug...
> 
> 方案1：看看能不能通过docker运行yutto，是否会出错？ 方案2：参考下README最下面的贡献方式，在poetry这个环境下运行是否会出错，如果出错，改下代码可以在报错的地方把InvalidURL的上下文输出一下

改代码找出毛病了，应该是我在`.zprofile`中写了HTTP_PROXY的键值，我把这个键值注释掉就可以了，多谢

**Comment by lc4t** [comment]
ok好的~
