### ISSUE TITLE
🐛 yutto好像下载不了

### ISSUE THREAD

**Issue by xianweibo** [yutto-dev/yutto#183]
### 问题简述

```
root@dockerforai:~/bilili-main# docker run --rm -it -v /video/video:/app siguremo/yutto -b https://space.bilibili.com/1626203278/video
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 WARN  抓取失败（ClientConnectorError），正在重试，剩余 2 次
 WARN  抓取失败（ClientConnectorError），正在重试，剩余 1 次
 WARN  抓取失败（ClientConnectorError），正在重试，剩余 0 次
Traceback (most recent call last):
  File "/usr/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/yutto/__main__.py", line 57, in main
    run(args_list)
  File "/usr/lib/python3.11/site-packages/yutto/utils/funcutils/as_sync.py", line 34, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yutto/__main__.py", line 248, in run
    url = await Fetcher.get_redirected_url(session, url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yutto/utils/fetcher.py", line 48, in connect_n_times
    raise MaxRetryError("超出最大重试次数！")
yutto.exceptions.MaxRetryError: 超出最大重试次数！
root@dockerforai:~/bilili-main# 
```

### 复现方式

```bash
docker run --rm -it -v /video/video:/app siguremo/yutto -b https://space.bilibili.com/1626203278/video
```

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  yutto: yutto 版本号 (`yutto -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by symant233** [comment]
用这个命令重装再试下
```
pip install git+https://github.com/yutto-dev/yutto@main
```
