### ISSUE TITLE
🐛 空间下载出问题了 报page error

### ISSUE THREAD

**Issue by xianweibo** [yutto-dev/yutto#229]
### 问题简述

docker run --rm -it -v /tmp/video:/app siguremo/yutto -b https://space.bilibili.com/40656188/video -q 120

root@dockerforai:/data/video# docker run --rm -it -v /data/video:/app siguremo/yutto -b https://space.bilibili.com/1688515694/video
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 UP 主投稿视频  严肃的英语
Traceback (most recent call last):
  File "/opt/venv/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/__main__.py", line 58, in main
    run(args_list)
  File "/opt/venv/lib/python3.11/site-packages/yutto/utils/funcutils/as_sync.py", line 37, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/__main__.py", line 275, in run
    download_list = await extractor(client, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/extractor/_abc.py", line 49, in __call__
    return await self.extract(client, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/extractor/user_all_ugc_videos.py", line 41, in extract
    for avid in await get_user_space_all_videos_avids(client, self.mid):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/api/space.py", line 35, in get_user_space_all_videos_avids
    total = math.ceil(json_data["data"]["page"]["count"] / ps)
                      ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'page'
root@dockerforai:/data/video# docker run --rm -it -v /tmp/video:/app siguremo/yutto -b https://space.bilibili.com/40656188/video -q 120

 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 UP 主投稿视频  小O音乐
Traceback (most recent call last):
  File "/opt/venv/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/__main__.py", line 58, in main
    run(args_list)
  File "/opt/venv/lib/python3.11/site-packages/yutto/utils/funcutils/as_sync.py", line 37, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/__main__.py", line 275, in run
    download_list = await extractor(client, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/extractor/_abc.py", line 49, in __call__
    return await self.extract(client, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/extractor/user_all_ugc_videos.py", line 41, in extract
    for avid in await get_user_space_all_videos_avids(client, self.mid):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/yutto/api/space.py", line 35, in get_user_space_all_videos_avids
    total = math.ceil(json_data["data"]["page"]["count"] / ps)
                      ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'page'
root@dockerforai:/data/video# 


空间下载出问题了


### 复现方式

docker run --rm -it -v /tmp/video:/app siguremo/yutto -b https://space.bilibili.com/40656188/video -q 120

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  yutto: yutto 版本号 (`yutto -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息


### 额外信息

_No response_

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> INFO 未提供 SESSDATA，无法下载会员专享剧集哟～

需要登录
