### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by shenbinglife** [yutto-dev/yutto#370]
### 问题简述

INFO  下载间隔 8 秒
 [4/17]  中配版2 波涛之下
 INFO  开始处理视频 中配版2 波涛之下
 INFO  共包含以下 18 个视频流：
 INFO  * 0 [AVC ] [3840x2160] < 4K 超清  > #3
 INFO    1 [HEVC] [3840x2160] < 4K 超清  > #3
 INFO    2 [AV1 ] [3840x2160] < 4K 超清  > #3
 INFO    3 [AVC ] [1920x1080] <1080P 高码率> #3
 INFO    4 [HEVC] [1920x1080] <1080P 高码率> #3
 INFO    5 [AV1 ] [1920x1080] <1080P 高码率> #3
 INFO    6 [AVC ] [1920x1080] <1080P 高清> #3
 INFO    7 [HEVC] [1920x1080] <1080P 高清> #3
 INFO    8 [AV1 ] [1920x1080] <1080P 高清> #3
 INFO    9 [AVC ] [1280x720 ] <720P 高清 > #3
 INFO   10 [HEVC] [1280x720 ] <720P 高清 > #3
 INFO   11 [AV1 ] [1280x720 ] <720P 高清 > #3
 INFO   12 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO   13 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO   14 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO   15 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO   16 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO   17 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 弹幕  ASS 弹幕已生成
 INFO  开始下载……
Traceback (most recent call last):
  File "/opt/venv/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/__main__.py", line 61, in main
    run(args_list)
  File "/opt/venv/lib/python3.12/site-packages/yutto/utils/funcutils/as_sync.py", line 39, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/__main__.py", line 173, in run
    current_download_state = await start_downloader(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/processor/downloader.py", line 376, in start_downloader
    await download_video_and_audio(client, video, video_path, audio, audio_path, options)
  File "/opt/venv/lib/python3.12/site-packages/yutto/processor/downloader.py", line 171, in download_video_and_audio
    await asyncio.gather(*coroutines)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/utils/asynclib.py", line 34, in __await__
    return (yield from self.coro.__await__())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/utils/fetcher.py", line 215, in download_file_with_offset
    async with client.stream(
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_client.py", line 1628, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_async/http2.py", line 167, in handle_async_request
    await self._response_closed(stream_id=stream_id)
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_async/http2.py", line 405, in _response_closed
    await self._max_streams_semaphore.release()
  File "/opt/venv/lib/python3.12/site-packages/httpcore/_synchronization.py", line 186, in release
    self._anyio_semaphore.release()
  File "/opt/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1886, in release
    raise ValueError("semaphore released too many times")
ValueError: semaphore released too many times

### 复现方式

yutto --download-interval 8 --no-color --no-progress -n 8 -w --no-subtitle --no-cover --no-chapter-info https://www.bilibili.com/video/xxx

### 环境信息

alpine:3.20
Python 3.12.7
yutto 2.0.0-rc.4
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
❓

**Comment by passerbya** [comment]
yutto --output-format mp4 -q 32 --no-danmaku --no-cover -tp BV1G4y6YXEuz -c 'XXX' -d bilili/temp/BV1G4y6YXEuz 'https://www.bilibili.com/video/BV1G4y6YXEuz'
 WARN  以非大会员身份登录，注意无法下载会员专享剧集喔～
 投稿视频  一个青椒2块钱，做一顿饭要多少？大胃带我们去非洲菜市场，今天这顿吃好的
 INFO  开始处理视频 BV1G4y6YXEuz
 INFO  共包含以下 12 个视频流：
 INFO    0 [HEVC] [1920x1080] <1080P 高清> #3
 INFO    1 [AVC ] [1920x1080] <1080P 高清> #3
 INFO    2 [AV1 ] [1920x1080] <1080P 高清> #3
 INFO    3 [HEVC] [1280x720 ] <720P 高清 > #3
 INFO    4 [AVC ] [1280x720 ] <720P 高清 > #3
 INFO    5 [AV1 ] [1280x720 ] <720P 高清 > #3
 INFO    6 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO  * 7 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO    8 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO    9 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO   10 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO   11 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 字幕  中文（自动生成） 字幕已全部生成
 INFO  开始下载……
Traceback (most recent call last):━━━━━━━━━━━━━━━━ 128.00 KiB/114.51 MiB 508.68 KiB/s  
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 148, in handle_async_request
    status, headers = await self._receive_response(
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 292, in _receive_response
    event = await self._receive_stream_event(request, stream_id)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 333, in _receive_stream_event
    await self._receive_events(request, stream_id)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 367, in _receive_events
    await self._receive_remote_settings_change(event)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 398, in _receive_remote_settings_change
    await self._max_streams_semaphore.release()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_synchronization.py", line 159, in release
    self._anyio_semaphore.release()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 383, in release
    raise ValueError("semaphore released too many times")
ValueError: semaphore released too many times

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/yutto/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/__main__.py", line 57, in main
    run(args_list)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/utils/funcutils/as_sync.py", line 39, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/root/miniconda3/envs/yutto/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/yutto/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/__main__.py", line 169, in run
    current_download_state = await start_downloader(
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/processor/downloader.py", line 376, in start_downloader
    await download_video_and_audio(client, video, video_path, audio, audio_path, options)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/processor/downloader.py", line 171, in download_video_and_audio
    await asyncio.gather(*coroutines)
  File "/root/miniconda3/envs/yutto/lib/python3.9/asyncio/tasks.py", line 688, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/utils/asynclib.py", line 34, in __await__
    return (yield from self.coro.__await__())
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/yutto/utils/fetcher.py", line 215, in download_file_with_offset
    async with client.stream(
  File "/root/miniconda3/envs/yutto/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_client.py", line 1628, in stream
    response = await self.send(
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 167, in handle_async_request
    await self._response_closed(stream_id=stream_id)
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_async/http2.py", line 405, in _response_closed
    await self._max_streams_semaphore.release()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/httpcore/_synchronization.py", line 159, in release
    self._anyio_semaphore.release()
  File "/root/miniconda3/envs/yutto/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 383, in release
    raise ValueError("semaphore released too many times")
ValueError: semaphore released too many times

我也遇到了这个问题
