### ISSUE TITLE
🐛 下载12集的番剧ss48591获取metadata出错

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [yutto-dev/yutto#379]
### 问题简述

获取metadata时报错

### 复现方式

yutto -q 80 -df xml --no-subtitle  --with-metadata -b https://www.bilibili.com/bangumi/play/ss48591

### 环境信息

-  OS: Windows 10 22H2
-  Python: 3.10.9
-  yutto: 2.0.0-rc5

### 额外信息

```bash
 番剧  拾荒者统治
 INFO  全 12 话
 INFO  已选择第 1 话
 DEBUG  Fetch json: https://api.bilibili.com/pgc/player/web/v2/playurl?avid=&bvid=BV1SEpje5EV7&cid=25798772702&qn=127&fnver=0&fnval=4048&fourk=1&support_multi_audio=true&from_client=BROWSER
 DEBUG  Fetch text: http://comment.bilibili.com/25798772702.xml
 DEBUG  Fetch bin: https://i0.hdslb.com/bfs/bangumi/image/07da4653e1b869658171ece30cab05fe4a592158.png
 [1/1]  第1话 信号
 INFO  开始处理视频 第1话 信号
 INFO  共包含以下 15 个视频流：
 INFO    0 [HEVC] [1920x1080] <1080P 高码率> #3
 INFO    1 [AVC ] [1920x1080] <1080P 高码率> #3
 INFO    2 [AV1 ] [1920x1080] <1080P 高码率> #3
 INFO    3 [HEVC] [1920x1080] <1080P 高清> #3
 INFO  * 4 [AVC ] [1920x1080] <1080P 高清> #3
 INFO    5 [AV1 ] [1920x1080] <1080P 高清> #3
 INFO    6 [HEVC] [1280x720 ] <720P 高清 > #3
 INFO    7 [AVC ] [1280x720 ] <720P 高清 > #3
 INFO    8 [AV1 ] [1280x720 ] <720P 高清 > #3
 INFO    9 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO   10 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO   11 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO   12 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO   13 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO   14 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 弹幕  XML 弹幕已生成
 描述文件  NFO 媒体描述文件已生成
 DEBUG  Get size: https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000 88710039
 DEBUG  Get size: https://cn-zjhz3-wasu-bcache-08.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=3a7a9070dcb960b1e011288b499c575b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20015&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=26456&logo=80000000 38255817
 INFO  开始下载……
 DEBUG  Start download (offset 1048576, number of mirrors 2) https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000
 DEBUG  Start download (offset 524288, number of mirrors 2) https://cn-zjhz3-wasu-bcache-08.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=3a7a9070dcb960b1e011288b499c575b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20015&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=26456&logo=80000000
 DEBUG  Start download (offset 1572864, number of mirrors 2) https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000
 DEBUG  Start download (offset 1048576, number of mirrors 2) https://cn-zjhz3-wasu-bcache-08.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=3a7a9070dcb960b1e011288b499c575b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20015&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=26456&logo=80000000
 DEBUG  Start download (offset 2097152, number of mirrors 2) https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000
 DEBUG  Start download (offset 1572864, number of mirrors 2) https://cn-zjhz3-wasu-bcache-08.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=3a7a9070dcb960b1e011288b499c575b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20015&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=26456&logo=80000000
 DEBUG  Start download (offset 2621440, number of mirrors 2) https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000
 DEBUG  Start download (offset 2097152, number of mirrors 2) https://cn-zjhz3-wasu-bcache-08.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=3a7a9070dcb960b1e011288b499c575b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20015&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=26456&logo=80000000
 DEBUG  Start download (offset 3145728, number of mirrors 2) https://cn-zjhz3-wasu-bcache-06.bilivideo.com/upgcxcode/02/27/25798772702/25798772702-1-100050.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1730748635&gen=playurlv2&os=bcache&oi=979658488&trid=00006d2b166ec31341ebba19d98b3057268fp&mid=543814248&platform=pc&og=08&upsig=81e1627d3ee6ea28273011f5dceb1d1a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=20013&bvc=vod&nettype=0&orderid=0,3&buvid=CFC22AC4-098B-4ACB-403B-380CDEBF0F7635225infoc&build=0&f=p_0_0&agrr=0&bw=61348&logo=80000000
Traceback (most recent call last):
  File "c:\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\python310\lib\site-packages\yutto\__main__.py", line 254, in <module>
    main()
  File "c:\python310\lib\site-packages\yutto\__main__.py", line 57, in main
    run(args_list)
  File "c:\python310\lib\site-packages\yutto\utils\funcutils\as_sync.py", line 39, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "c:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\python310\lib\site-packages\yutto\__main__.py", line 169, in run
    current_download_state = await start_downloader(
  File "c:\python310\lib\site-packages\yutto\processor\downloader.py", line 376, in start_downloader
    await download_video_and_audio(client, video, video_path, audio, audio_path, options)
  File "c:\python310\lib\site-packages\yutto\processor\downloader.py", line 171, in download_video_and_audio
    await asyncio.gather(*coroutines)
  File "c:\python310\lib\asyncio\tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "c:\python310\lib\site-packages\yutto\utils\asynclib.py", line 34, in __await__
    return (yield from self.coro.__await__())
  File "c:\python310\lib\site-packages\yutto\utils\fetcher.py", line 215, in download_file_with_offset
    async with client.stream(
  File "c:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "c:\python310\lib\site-packages\httpx\_client.py", line 1628, in stream
    response = await self.send(
  File "c:\python310\lib\site-packages\httpx\_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "c:\python310\lib\site-packages\httpx\_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\python310\lib\site-packages\httpx\_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "c:\python310\lib\site-packages\httpx\_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "c:\python310\lib\site-packages\httpx\_transports\default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "c:\python310\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "c:\python310\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "c:\python310\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "c:\python310\lib\site-packages\httpcore\_async\http2.py", line 167, in handle_async_request
    await self._response_closed(stream_id=stream_id)
  File "c:\python310\lib\site-packages\httpcore\_async\http2.py", line 405, in _response_closed
    await self._max_streams_semaphore.release()
  File "c:\python310\lib\site-packages\httpcore\_synchronization.py", line 186, in release
    self._anyio_semaphore.release()
  File "c:\python310\lib\site-packages\anyio\_backends\_asyncio.py", line 1886, in release
    raise ValueError("semaphore released too many times")
ValueError: semaphore released too many times
```

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by ZzzzzzzSkyward** [comment]
补充：不附加metadata只能下载11集，第一次下载7集，第二次以后下到11集就相同报错。

**Comment by ZzzzzzzSkyward** [comment]
经调查原因是httpcore里定义的MAX_CONCURRENT_STREAMS=100远大于服务器连接数。将Lib\site-packages\httpcore\_async\http2.py里的数值修改为`h2.settings.SettingCodes.MAX_CONCURRENT_STREAMS: 4,`可避免改问题。但这个参数貌似不能从外部修改。

**Comment by OcrSu** [comment]
我这也遇到了，蹲一手新版本release
