### ISSUE TITLE
🐛 ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by XcantloadX** [yutto-dev/yutto#95]
### 问题简述

只在 P178 出问题
``` 
[178/215]  6.【讲义50】【洛伦兹力】概念
 INFO  开始处理视频 6.【讲义50】【洛伦兹力】概念
 INFO  共包含以下 12 个视频流：
 INFO  * 0 [AVC ] [1920x1080] <1080P 高清> #3
 INFO    1 [HEVC] [1920x1080] <1080P 高清> #3
 INFO    2 [AV1 ] [1920x1080] <1080P 高清> #3
 INFO    3 [AVC ] [1280x720 ] <720P 高清 > #3
 INFO    4 [HEVC] [1280x720 ] <720P 高清 > #3
 INFO    5 [AV1 ] [1280x720 ] <720P 高清 > #3
 INFO    6 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO    7 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO    8 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO    9 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO   10 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO   11 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 弹幕  ASS 弹幕已生成
 INFO  开始下载……
 DEBUG  Start download (offset 0) https://cn-sxty-cm-02-02.bilivideo.com/upgcxcode/29/85/314338529/314338529_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1666188276&gen=playurlv2&os=bcache&oi=3084308406&trid=0000b81cb7583ae84816bb42b740c95333eau&mid=0&platform=pc&upsig=2b37900b66fb12c3b02b3042ba7138ff&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=6501&bvc=vod&nettype=0&orderid=0,3&agrr=0&bw=29385&logo=80000000
 DEBUG  Start download (offset 0) https://cn-sxty-cm-02-02.bilivideo.com/upgcxcode/29/85/314338529/314338529_nb2-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1666188276&gen=playurlv2&os=bcache&oi=3084308406&trid=0000b81cb7583ae84816bb42b740c95333eau&mid=0&platform=pc&upsig=e0ba01f9260c924f39e59093072eb9f7&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=6501&bvc=vod&nettype=0&orderid=0,3&agrr=0&bw=16297&logo=80000000
Traceback (most recent call last):
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\Scripts\yutto.exe\__main__.py", line 7, in <module>
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\__main__.py", line 46, in main
    run(args_list)
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\utils\funcutils\as_sync.py", line 33, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\__main__.py", line 195, in run
    await start_downloader(
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\processor\downloader.py", line 243, in start_downloader
    await download_video_and_audio(session, video, video_path, audio, audio_path, options)
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\processor\downloader.py", line 129, in download_video_and_audio
    await asyncio.gather(*coroutines)
  File "C:\Users\ZhouXiaokang\AppData\Local\Programs\Python\Python310\lib\site-packages\yutto\processor\progressbar.py", line 81, in show_progress
    size_now / total_size,
ZeroDivisionError: division by zero
sys:1: RuntimeWarning: coroutine 'extract_ugc_video_data' was never awaited
PS E:\>
```

### 复现方式

yutto -b "https://space.bilibili.com/23630128/channel/seriesdetail?sid=340933" -x=no --debug

### 环境信息

-  OS: Win11 22H2
-  Python: 3.10.5
-  yutto: 2.0.0-beta.15
-  FFmpeg: 
```
ffmpeg version N-91814-gc4cda4eb87 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20180813
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 19.100 / 56. 19.100
libavcodec     58. 27.101 / 58. 27.101
libavformat    58. 18.100 / 58. 18.100
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 27.100 /  7. 27.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100
```
-  如果是显示相关问题
    -  Shell: Powershell
    -  Terminal: Windows Terminal
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
唔，是这个视频吧 https://www.bilibili.com/video/BV1uK4y1T7ox?p=6

直接下载这个视频没有出现任何问题，应该不是视频的问题，只是网络的问题导致没有成功获取到正确的 size

```bash
yutto 'https://www.bilibili.com/video/BV1uK4y1T7ox?p=6'
```

可以试试重新运行一遍
